spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              predicates:
                - Path=/user/**
              uri: lb://AUTH-SERVICE
              filters:
                - StripPrefix=1
            - id: product-service
              predicates:
                - Path=/product/**
              uri: lb://PRODUCT-SERVICE
              filters:
                - StripPrefix=1
server:
  port: 9090
jwt:
  app:
    jwt-secret: 2b9f6d7a1d5c0a99c7d8e22b3f441acfe7b1aa6d02b57d6c9c89af12d8bb23f1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
