spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/product-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8088